title: UDAY KUMAR KARAMPUDI
logo: /assets/img/headshot_circle.png
description: "Full Stack Developer | Java, Spring Boot, React | Cloud Deployment with AWS | Building Scalable Web Applications"
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
