title: Uday Kumar Karampudi
logo: /assets/img/headshot_circle.png
description: "Data Analyst | Expertise in Python, SQL, Machine Learning & Data Visualization | Skilled in Power BI, Tableau, Azure & Cloud Analytics | Delivering Data-Driven Solutions to Drive Business Insights"
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
