title: Uday Kumar Karampudi
logo: /assets/img/headshot_circle.png
description: "Data Analyst | Python | SQL | Machine Learning | Tableau | Power BI"
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
